### ISSUE TITLE
Styling für @@historyview

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/plonetheme.blueberry#13]
Die View wird bereits in einem Kundenprojekt gestylt:

Bsp.:

![bildschirmfoto 2016-02-09 um 17 11 14 1](https://cloud.githubusercontent.com/assets/557005/12922029/2ae617b2-cf50-11e5-8166-7e94fddd222b.png)

```css
#content-history {
  .historyLinks {
    display: none;
  }
  ul {
    @include ul(plain);
  }
  .historyRecord {
    padding-bottom: $padding-horizontal;
    border-bottom: 1px solid $gray-light;
    margin-bottom: $margin-horizontal;
  }
}
```
